name: MaUI App Release

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest
    
    env:
      Project_Path: ./WhatIsThis/WhatIsThis.sln
      GH_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Update App Version
      run: |
        $xml=[xml](Get-Content ./WhatIsThis/WhatIsThis.csproj)
        $node=$xml.SelectSingleNode("//ApplicationVersion")
        $node.InnerText = ${{ vars.VERSIONCODE }}
        $xml.Save("./WhatIsThis/WhatIsThis.csproj")
      shell: pwsh
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore workloads
      run: dotnet workload restore --project $env:Project_Path
    - name: Restore workloads
      run: dotnet workload install maui-android
    - name: Restore dependencies
      run: dotnet restore $env:Project_Path
    - name: Build
      run: dotnet publish $env:Project_Path -f net7.0-android -c Release -p:AndroidSigningKeyPass=${{ secrets.SIGNING_PASSWORD }} -p:AndroidSigningStorePass=${{ secrets.SIGNING_PASSWORD}}
    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.companyname.whatisthis
        releaseFiles:  ./WhatIsThis/bin/Release/net7.0-android/publish/com.companyname.whatisthis-Signed.aab
        track: production
        inAppUpdatePriority: 2
    - name: Update Version Variable
      run: |
        gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/SelminBiop/education-helpers/actions/variables/VERSIONCODE -f name="VERSIONCODE" -f value="$((${{ vars.VERSIONCODE }} + 1))" 
