name: MaUI App Release

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest
    
    env:
      Project_Path: ./WhatIsThis/WhatIsThis.sln
      GH_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Update App Version
      run: |
        $xml=[xml](Get-Content ./WhatIsThis/WhatIsThis.csproj)
        $node=$xml.SelectSingleNode("//ApplicationVersion")
        $node.InnerText = ${{ vars.VERSIONCODE }}
        $xml.Save("./WhatIsThis/WhatIsThis.csproj")
      shell: pwsh
    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v3
    #  with:
    #    dotnet-version: 7.0.x
   # - name: Restore workloads
   #   run: dotnet workload restore --project $env:Project_Path
   # - name: Restore iOS workloads
   #   run: dotnet workload install ios maccatalyst maui-android
   # - name: Restore dependencies
   #   run: dotnet restore $env:Project_Path
   # - name: Build
    #  run: dotnet build $env:Project_Path --no-restore
    - name: "Increment VersionCode"
      run: |
        echo "incrementedVersion = $((${{ vars.VERSIONCODE }} + 1))" >> $GITHUB_ENV
        echo $((${{ vars.VERSIONCODE }} + 1))
    - name: Update Version Variable
      env:
        Incremented_Version: env.incrementedVersion
      run: |
        echo $Incremented_Version
        gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/SelminBiop/education-helpers/actions/variables/VERSIONCODE -f name="VERSIONCODE" -f value="${Incremented_Version}" 
